src/LA/system_solvers_large.cpp

Piccola modifica testata e funzionante.

LA: add solution dump to SystemSolver 

---

README.md

If we like it, we can merge on master

Add Travis status badge in Readme.md

---

src/containers/piercedKernel.hpp
src/containers/piercedKernel.tpp
src/patchkernel/patch_kernel.cpp

PiercedStoraged was not properly synchronized after some PiercedVector operations.

containers: fix issues with PiercedStorage synchronization

---

src/POD/pod_common.hpp
src/SA/LIFOStack.tpp
src/SA/SortAlgorithms.hpp
src/levelset/levelSetBoolean.cpp
src/levelset/levelSetBoolean.hpp
src/levelset/levelSetCommon.hpp
src/patchkernel/patch_kernel.cpp
src/patchkernel/patch_kernel_parallel.cpp

Miscellaneuous fixes and micro-optimizations that I've collected in the past weeks.

bitpit: miscellaneuous fixes and micro-optimizations

---

src/containers/piercedVectorStorage.tpp
src/patchkernel/patch_kernel.cpp
src/voloctree/voloctree.cpp

Optimize interface and vertex deletion.

patchkernel: optimize adaption

---

src/patchkernel/patch_kernel.cpp
src/voloctree/voloctree.cpp

Added some assertion to silence errors reported by Coverity.

bitpit: silence errors reported by Coverity

---

.travis.yml

A couple of fixes to the Travis configuration file.

travis: fix configuration file

---

src/LA/system_solvers_large.cpp

It works smooth in my application.

LA: move KSP prefix setting after KSP creation

---

src/LA/system_solvers_large.cpp
src/LA/system_solvers_large.hpp
src/discretization/stencil_solver.cpp
src/discretization/stencil_solver.hpp

Add functions to update all the elements of the system solver and of the stencil solver.

discretization: add a function to update the whole solver

---

src/surfunstructured/surfunstructured.cpp

Fix cell PIDs assignment during multi-solid STL import.

surfunstructured: fix import multi-solid STL

---

src/IO/STL.cpp
src/IO/STL.hpp
src/patchkernel/patch_kernel_parallel.cpp
src/surfunstructured/surfunstructured.cpp
src/surfunstructured/surfunstructured.hpp
test/surfunstructured/test_surfunstructured_00008.cpp
test/surfunstructured/test_surfunstructured_parallel_00002.cpp

Enable parallel STL export (both single and multi solid exports are implemented).
Parallel export is tested in "test_surfunstructured_parallel_00002".

surfunstructured: enable parallel STL export

---

src/common/commonUtils.hpp

It is now possible to specify both absolute and relative tolerances.
@edoardolombardi Are you using this function in your applications? If so, are the changes are fine with you?

common: rework function that checks if two floating point numbers are equal

---

src/voloctree/voloctree.cpp

Avoid using "find*AllCodimensionNeighbours" functions and use PABLO low-level function directly.

voloctree: optimize neighbour search

---

src/CG/CG_elem.cpp

CG: bug fix in intersect segment box method

---

src/volcartesian/volcartesian.cpp
test/volcartesian/CMakeLists.txt
test/volcartesian/test_volcartesian_00001.cpp
test/volcartesian/test_volcartesian_00004.cpp

I've added a test for the light memory mode and integrated the documentation with a paragraph briefly explaining the difference between normal and light memory mode.

volcartesian: add a test for light memory mode

---

src/PABLO/LocalTree.cpp
src/PABLO/LocalTree.hpp
src/PABLO/Octant.cpp
src/PABLO/ParaTree.cpp
src/PABLO/ParaTree.hpp

With these changes, find-neighbours functions are about 20% faster.

PABLO: optimize find-neighbours functions

---

examples/PABLO_example_00006.cpp
src/IO/VTK.hpp
src/IO/logger.cpp
src/LA/matrix_utilities.tpp
src/LA/system_matrix.cpp
src/LA/system_solvers_large.cpp
src/PABLO/LocalTree.cpp
src/PABLO/ParaTree.cpp
src/PABLO/ParaTree.hpp
src/POD/pod_voloctree.cpp
src/common/binaryUtils.tpp
src/communications/communications.cpp
src/containers/flatVector2D.tpp
src/discretization/reconstruction.cpp
src/discretization/stencil.tpp
src/discretization/stencil_solver.tpp
src/levelset/levelSetSegmentation.cpp
src/patchkernel/element.tpp
src/patchkernel/patch_kernel.cpp
src/patchkernel/patch_kernel_parallel.cpp
src/patchkernel/patch_skd_tree.cpp
src/patchkernel/surface_skd_tree.cpp
src/voloctree/voloctree.cpp
src/voloctree/voloctree_mapper.cpp
src/voloctree/voloctree_parallel.cpp
test/CMakeLists.txt
test/communications/test_communications_parallel_00001.cpp
test/surfunstructured/test_surfunstructured_parallel_00001.cpp
test/voloctree/test_voloctree_parallel_00001.cpp
test/voloctree/test_voloctree_parallel_00002.cpp

Miscellaneous fixes and improvements to the documentation.

Improve documentation

---

src/volcartesian/volcartesian.cpp
src/volcartesian/volcartesian.hpp
test/volcartesian/CMakeLists.txt
test/volcartesian/test_volcartesian_00005.cpp

Degenerate patches are patches that have zero cells along one ore more directions.

volcartesian: add support for degenerate patches

---

src/CG/CG.hpp
src/CG/CG_elem.cpp

Add functions to check the intersection between boxes and sphere/circles.

CG: add functions to check the intersection between boxes and sphere/circles

---

src/IO/configuration.hpp
src/common/stringUtils.hpp
src/communications/communications.cpp

Some fixes/cleanups cherry picked from pull request #144.

bitpit: fix/cleanup header inclusion

---

src/levelset/levelSet.cpp
src/levelset/levelSet.hpp
src/levelset/levelSetCachedObject.cpp
src/levelset/levelSetKernel.cpp
src/levelset/levelSetKernel.hpp
src/levelset/levelSetObject.cpp
src/levelset/levelSetObject.hpp
src/levelset/levelSetSegmentation.cpp
test/levelset/test_levelset_parallel_00001.cpp
test/levelset/test_levelset_parallel_00002.cpp

There is now a single function that handles both mesh adaption and mesh partitioning.

levelset: simplify update

---

src/levelset/levelSetSegmentation.cpp

Border edges doesn't have a neighbour.

levelset: fix evaluation of normal on border edges

---

src/PABLO/LocalTree.cpp
src/PABLO/ParaTree.cpp

I've removed some unneeded vector swaps.

PABLO: micro optimize 2:1 local balancing 

---

src/IO/configuration_JSON.cpp

this pull fix a wrong call in assert (row 106) of configuration_JSON.cpp.
The error is visible only compiling in Debug mode.

IO: fix in configuration_JSON

---

src/containers/piercedKernel.hpp
src/containers/piercedKernel.tpp
src/containers/piercedStorage.cpp
src/containers/piercedStorage.hpp
src/containers/piercedStorage.tpp
src/containers/piercedVector.tpp

Fixes to the dump/restore and to the registration/unregistration of the pierced storage.

containers: miscellaneous fix for the pierced storage

---

src/PABLO/ParaTree.cpp
src/PABLO/ParaTree.hpp

The footer doesn't contain useful information.

PABLO: remove final PABLO footer

---

src/levelset/levelSetCommon.hpp
src/levelset/levelSetObject.hpp
src/levelset/levelSetStorage.tpp

Fixes compilation of bitpit on gcc 4.8.5.

Fix compilation for on old gcc compilers

---

src/LA/system_solvers_large.cpp
src/LA/system_solvers_large.hpp
src/discretization/stencil_solver.cpp
src/discretization/stencil_solver.hpp
src/discretization/stencil_solver.tpp
src/patchkernel/patch_kernel.cpp
src/patchkernel/patch_kernel.hpp

The rework allows DiscretizationStencilSolverAssembler derived classes to perform a fine-grain initialization.

discretization: rework assembler initialization

---

src/IO/VTKRectilinear.cpp
src/IO/VTKUnstructured.cpp
src/LA/system_solvers_large.cpp
src/containers/proxyVector.hpp
src/discretization/stencil.cpp
src/discretization/stencil.hpp
src/discretization/stencil.tpp
src/discretization/stencil_solver.hpp
src/discretization/stencil_solver.tpp

Some optimizations to the stencils.

discretization: optimize stencils

---

src/patchkernel/patch_kernel.cpp
src/patchkernel/patch_kernel.hpp
test/integration_tests/surfunstructured/test_surfunstructured_00001.cpp
test/integration_tests/volunstructured/test_volunstructured_00001.cpp

Identification of duplicate cells is based on vertex ids: a cell is a duplicate of another cell if it shares the same vertex ids.

Add a function to find duplicate cells

---

src/patchkernel/patch_kernel.hpp
src/patchkernel/patch_kernel_parallel.cpp

Same as #337, but with the commits squashed together. Creating a new pull request was the fastest wat to squash the commits together.

patchkernel: fix incorrect conversion

---

src/patchkernel/patch_kernel.cpp

This ensures that memory hold by empty alteration flags will be released when the patch is squzeed.

patchkernel: add alteration flags to the data structures that will be squeezed

---

src/containers/flatVector2D.tpp

Let's leave to the standard library the burden of optimizing the insertion of new values.

containers: simplify FlatVector2D::pushBack function

---

examples/voloctree_adaptation_example_00001.cpp
src/LA/system_matrix.cpp
src/LA/system_solvers_large.cpp
src/PABLO/LocalTree.cpp
src/PABLO/ParaTree.cpp
src/common/commonUtils.cpp
src/common/commonUtils.hpp
src/common/commonUtils.tpp
src/voloctree/voloctree.cpp
test/integration_tests/PABLO/test_PABLO_parallel_00006.cpp
test/integration_tests/volunstructured/test_volunstructured_parallel_00005.cpp

Miscellaneous fixes for problems discovered compiling bitpit with GCC 12.2.

Fixes for problems identified by GCC 12.2

---

src/POD/pod_voloctree.cpp
src/common/logger.cpp
src/discretization/reconstruction.cpp
src/levelset/levelSet.cpp
src/levelset/levelSetCachedObject.cpp
src/levelset/levelSetCartesianKernel.cpp
src/levelset/levelSetSegmentationObject.cpp
src/patchkernel/patch_kernel_parallel.cpp
src/patchkernel/patch_skd_tree.cpp
src/patchkernel/surface_kernel.cpp
src/voloctree/voloctree.cpp

As the title says: miscellaneous fixes to Doxygen documentation.

Miscellaneous fixes to Doxygen documentation

---

src/CG/CG.hpp
src/CG/CG_elem.cpp
src/IO/STL.cpp
src/patchkernel/patch_kernel.cpp
src/patchkernel/patch_kernel.hpp
src/patchkernel/vertex.cpp
src/patchkernel/vertex.hpp
src/volcartesian/volcartesian.cpp
src/volcartesian/volcartesian.hpp
test/integration_tests/CG/test_CG_00002.cpp

The function allows to rotate a patch along a specified axis.

patchkernel: add function to rotate the patch

---

.travis.yml
examples/RBF_example_00001.cpp

CI will now build also the examples and will no longer send notification to the Slack channel.

Update travis configuration

---

src/patchkernel/patch_kernel_parallel.cpp

Pull request #425 introduced support for partitioning empty patches with METIS. However, after the pull request was merged, we experienced some random deadlocks when try to partition empty patches. The reason is that, even if we are partitioning an empty patch, we still need to go through the whole preparation to make sure all internal data structures are properly initialized.

patchkernel: fix partitionig of empty patches

---

src/IO/configuration.hpp
src/IO/configuration_config.hpp
src/RBF/rbf.cpp

It is still not possible to compile the master branch of bitpit with MSVC, however here are some fixes that will be needed for achieving this goal.

Miscellanueous fixes needed for compiling with MSVC

---

CMakeLists.txt

Now that branch 1.9 is created, bump the version in master.

bitpit: bump version to 1.10.0-devel

---

CMakeLists.txt

Now that branch 1.10 is created, bump the version in master.

bitpit: bump version to 2.0.0-devel

---

src/RBF/rbf.cpp

Small optimizations found by code inspection.

RBF: miscellanueous optimizations

---

.travis.yml
src/CG/CG_elem.cpp
src/IO/STL.cpp
src/IO/VTKUnstructured.cpp
src/LA/system_solvers_large.hpp
src/PABLO/Map.cpp
src/PABLO/Map.hpp
src/POD/pod.cpp
src/POD/pod.hpp
src/SA/PQueue.tpp
src/common/logger.cpp
src/common/stringUtils.hpp
src/common/stringUtils.tpp
src/containers/piercedStorage.tpp
src/discretization/stencil_solver.tpp
src/levelset/levelSetBooleanObject.tpp
src/levelset/levelSetObject.cpp
src/levelset/levelSetSegmentationObject.cpp
src/voloctree/voloctree.cpp
src/voloctree/voloctree_mapper.cpp
test/integration_tests/common/test_common_00001.cpp

Miscellaneous fixes for warnings reported by Coverity.

Miscellaneous fixes for warnings reported by Coverity

---

src/containers/piercedKernel.tpp
src/patchkernel/adaption.cpp
src/patchkernel/adaption.hpp
src/patchkernel/patch_kernel.cpp
src/patchkernel/patch_kernel_parallel.cpp
src/volcartesian/volcartesian.cpp
src/volcartesian/volcartesian.hpp
src/voloctree/voloctree.cpp
src/voloctree/voloctree_mapper.cpp
src/voloctree/voloctree_mapper.hpp
src/voloctree/voloctree_parallel.cpp

Mainly some changes to the data structure that keeps track of element changes that will make it easier to add support for tracking adaptation of interface/vertex.

patchkernel: preliminary changes for tracking adaptation of interface/vertex

---

CMakeLists.txt

Now that branch 2.0 is created, bump the version in master.

bitpit: bump version to 2.1.0-devel

---

src/IO/GenericIO.hpp
src/common/logger.cpp
src/common/logger.hpp
test/integration_tests/operators/test_operators_00001.cpp

bitpit: clean-up includes 

---

CMakeLists.txt

Now that branch 2.1 is created, bump the version in master.

bitpit: bump version to 2.2.0-devel
