src/levelset/levelSetSegmentation.cpp

This correction avoids isolated groups of solid cells outside the bodies

levelset: use normal for computing distance sign

---

test/CMakeLists.txt

Beginning with version 3.0, OpenMPI's mpirun refuses to start more processes than there are physical processor cores on the machine.
To allow oversubcribing, the 'OMPI_MCA_rmaps_base_oversubscribe' environment variable can be set to 1.

cmake: allow to oversubscribe the machine during MPI tests

---

src/levelset/levelSetCachedObject.cpp
src/patchkernel/patch_info.cpp
src/patchkernel/patch_kernel_parallel.cpp

Use reference when iterating over lists of exchange sources and targets.

bitpit: fix range loop iterations over list of exchange sources and targets

---

src/IO/VTK.hpp

Constructors of VTKRectilinearGrid were erroneously declared as protected.

IO: fix declarations of VTKRectilinearGrid constructors

---

src/PABLO/LocalTree.cpp

In case of octree composed by root octant only, the neighbours research is not performed.

PABLO: fixed find neighbours methods for root octant

---

src/PABLO/ParaTree.cpp

Fixed updating of iterators for internal and border of process octants during ghosts recovering

PABLO: fix iterators in update ghosts method

---

src/patchkernel/patch_info.cpp
src/patchkernel/patch_info.hpp

Add a function to get the local offset of consecutive numbering.

patchkernel: allow to get local offset of consecutive numbering

---

src/IO/binary_archive.cpp
src/IO/binary_archive.hpp

Add functions to get the path of a binary archive.

IO: add functions to get the path of a binary archive

---

src/IO/VTK.hpp
src/IO/VTKUnstructured.cpp
src/patchkernel/patch_kernel.cpp

Data type of offset field should match the data type of the connectivity. 
This is the error raised by Paraview 5.8 while opening a VolOctree patch:
```
vtkXMLUnstructuredGridReader (0x5594e13b0b20): Cannot read cell data from Cells. Offsets and connectivity arrays must be the same type.
```
@haysam The change to the IO module is not strictly needed to fix the issue because PatchKernel is not using VTK homogeneous grids, but I think we shouldn't set the type of the offset field to UInt64 unconditionally (it may not match the data type of the connectivity field).

patchkernel: fix data types of VTK geometry fields

---

src/LA/system_matrix.cpp
src/LA/system_solvers_large.cpp
src/LA/system_solvers_large.hpp

Permutations are applied internally by the solver, this means that matrix permutations are applied when initializing the system, whereas permutations on the right hand side and on the solution are applied before solving the system and unapplied right after.
When the system is partitioned, only local permutations are supported.

LA: add support for custom rows/columns permutations

---

cmake/BITPITConfig.cmake.in

Low level dependencies should be found first.

cmake: use proper order when finding external dependencies

---

src/LA/system_matrix.cpp
src/LA/system_matrix.hpp
src/LA/system_solvers_large.cpp
src/LA/system_solvers_large.hpp
src/discretization/stencil_solver.cpp
src/discretization/stencil_solver.hpp

The class "StencilSolverAssembler" makes it possible to assemble the stencil solver without first assembly a temporary matrix. This reduce both the computational time and the memory requirements of the stencil solver. 
The class "StencilSolverAssembler" is used by the solver internally, thus the API has not changed.

discretization: optimize assembly of stencil solver

---

src/voloctree/voloctree_mapper.cpp

Fix inverse mapping re-communication

Fix voloctree mapper

---

src/LA/system_solvers_large.cpp

System update can alter only the values of the matrix, not its pattern. Instead of coding our own check that enforces this condition, it is simpler and much cheaper to set the "MAT_NEW_NONZERO_LOCATIONS" PETSc option to false after the first matrix assembly. This ensures no new non-zero entries can be added during system updates.
This banche starts from "discretization.update.all", the commit that implements this optimization is the last one in the series.

LA: optimize system update

---

src/LA/system_solvers_large.cpp

The condition to detect if system data structures need to be cleared was inverted.

LA: fix clearing system solver data structures

---

src/patchkernel/patch_kernel.cpp
src/patchkernel/patch_kernel.hpp
src/volcartesian/volcartesian.cpp
src/volcartesian/volcartesian.hpp
src/voloctree/voloctree.cpp
src/voloctree/voloctree.hpp

It is now possible scale the patch with respect to an arbitrary point.
@marcocisternino @edoardolombardi Can you double check that PABLO tree is properly scaled in VolOctree?

patchkernel: allow to scale the patch with respect to an arbitrary point

---

src/LA/system_solvers_large.cpp

Since the setUp was not properly marked as done, it was executed every time the function "solve" was called.

 LA: properly mark system set up as done at the end of "SystemSolver::setUp"

---

src/communications/communications.cpp

On some MPI implementaiotns (i.e., MPICH), the function MPI_Ibarrier can return a MPI_REQUEST_NULL if the communicator size is 1. Thus, it is not possible to use MPI_REQUEST_NULL as a sentinel value.
A separate boolean is introduced to track if the local exchange has completed.

communications: do not use MPI_REQUEST_NULL as sentinel value

---

src/LA/system_solvers_large.cpp
src/LA/system_solvers_large.hpp

PETSc option prefix is properly taken into account when setting debug options. Also, log view is now enabled using PETSc functions instead of PETSc options, this allows to enable the log view also if PetscInitialize function is called outside bitpit.

LA: fix set up of debug options

---

src/containers/piercedKernelIterator.hpp
src/containers/piercedStorageIterator.hpp
src/discretization/reconstruction.cpp

When evaluating the gradient stencil weight, the unused components (es. the third component of a two-dimensional reconstruction) is now explicitly set to zero. I prefer setting the unused components to zero inside bitpit, rather than in the external application using bitpit.

discretization: fix evaluation of stencil grantient weights

---

src/containers/flatVector2D.hpp
src/containers/flatVector2D.tpp
src/discretization/stencil.tpp

When initializing an empty stencil, the function that handles the initialization of the pattern and the weights should receive in input references to the null id and to the zero value (as opposed to pointers).

discretization: fix stencil initialization

---

src/patchkernel/patch_skd_tree.cpp
src/patchkernel/patch_skd_tree.hpp
src/patchkernel/surface_skd_tree.cpp
src/patchkernel/surface_skd_tree.hpp
src/patchkernel/volume_skd_tree.cpp
src/patchkernel/volume_skd_tree.hpp
test/surfunstructured/CMakeLists.txt
test/surfunstructured/test_surfunstructured_parallel_00006.cpp

Surface skd-tree searches work now properly on partitioned patches ("partitioned" means that the "PatchKernel::partition" function has been called before building the skd-tree).

 patchkernel: add support for parallel surface skd-tree searches

---

src/LA/system_solvers_large.cpp
src/LA/system_solvers_large.hpp
src/common/compiler.hpp
src/containers/flatVector2D.hpp
src/containers/flatVector2D.tpp
src/containers/proxyVector.hpp
src/containers/proxyVector.tpp
src/discretization/stencil.cpp
src/discretization/stencil.hpp
src/discretization/stencil.tpp
src/discretization/stencil_solver.cpp
src/discretization/stencil_solver.hpp
src/discretization/stencil_solver.tpp

The StencilBlock class can store weights of variable length. Weights are stored using std::vector containers, which is not optimal in terms of performances and memory usage. More efficient storage strategies need some fundamental changes to the DiscretizationStencil class and, if needed, they will be introduced in the future.

discretization: add a stencil to handle variable-length weights

---

src/patchkernel/patch_kernel_parallel.cpp

The size of buffer used for exchanging cells during partitioning was wrong.

patchkernel: fix size of buffer used for exchanging cells during partitioning

---

src/IO/VTK.cpp
src/IO/VTK.hpp
src/IO/VTKField.cpp

Some strings can be returned as constant references.

IO/VTK: return constant references whenever possible

---

src/IO/STL.cpp
src/IO/STL.hpp
src/IO/line_stream.cpp
src/IO/line_stream.hpp

The speedup is achieved using a custom stream instead of the std::stingstream. 
With these changes, the time it takes to generate a SurfUnstructured patch form an ASCII file of 450k triangles goes from 11.3 seconds to 9.3 seconds.

IO/STL: speedup reading of ASCII files

---

src/voloctree/voloctree.cpp

This reduces memory allocations during adaption.

voloctree: move vector declarations outside loop to reduce reallocations

---

src/patchkernel/patch_skd_tree.cpp
src/patchkernel/surface_skd_tree.cpp
src/patchkernel/surface_skd_tree.hpp

Use class members and heap allocated data structures to reduce temporary allocations performed by SkdTree searches.

patchkernel: reduce allocations performed during SkdTree searches

---

src/discretization/reconstruction.cpp
src/discretization/reconstruction.hpp

LAPACKE_dgesvd function silently allocates a workspace every time is called. Using the function dgesvd_ it is possible to store the workspace inside the ReconstructionAssembler class.

discretization: optimize evaluation of pseudo inverse

---

src/PABLO/Octant.cpp
src/discretization/reconstruction.cpp
src/discretization/stencil_solver.cpp
src/patchkernel/patch_info.cpp
src/patchkernel/patch_skd_tree.cpp

Fixes for errors found by Coverity.

bitpit: miscellaneous coverity fixes

---

src/discretization/reconstruction.cpp
src/discretization/reconstruction.hpp

Coefficients are now stored using a plain vector instead of a vector of vectors.

reconstruction: optimize storage for assembler equation coefficients

---

src/IO/logger.cpp

Logger settings were not properly restored after printing a message.

IO: properly restore logger settings after printing a message

---

src/CG/CG.hpp
src/CG/CG_elem.cpp
src/IO/logger.cpp
src/levelset/levelSetSegmentation.cpp
src/levelset/levelSetSegmentation.hpp
src/patchkernel/surface_kernel.cpp
src/patchkernel/surface_kernel.hpp

Some optimizations that should speedup generation of segmentation and reduce memory allocations:
- allow to pass the list of vertex neighbours to the PatchKernel functions that evaluate vertex normal, this avoids multiple evaluation of the neighbours when setting segmentation kernel surface;
- avoid storing both limited and unlimited vertex normals, only the one that will be used to evaluate segment information is now stored;
- store vertex normals using a PiercedStorage.

levelset: optimize evaluation of segmentation vertex normals

---

src/levelset/levelSetKernel.cpp
src/levelset/levelSetSegmentation.cpp
src/levelset/levelSetSegmentation.hpp
src/patchkernel/patch_kernel.cpp
src/patchkernel/patch_kernel.hpp
src/voloctree/voloctree.cpp
src/volunstructured/volunstructured.cpp
test/discretization/test_discretization_00001.cpp

There is no need to use a ProxyVector to store vertex coordinates, just use plain pointers.

patchkernel: simplify function that get vertex coordinates

---

doc/Doxyfile.in

Enabled support for LATEX math environment in doxygen documentation.
Tested (and works) with the most common LATEX environment (equation, align, etc.) and sigle-line formula.

doc: Enable support for LATEX in doxygen documentation

---

src/discretization/stencil.cpp
src/discretization/stencil.hpp
src/discretization/stencil.tpp

Stencils are now vector-like containers, it is no more possible to group items in buckets.

discretization: remove stencil buckets

---

src/CG/CG.hpp
src/CG/CG_elem.cpp
src/CG/CG_private.hpp

Fix the use of numerical tolerance to identify interesctions in CG module by adding an optional argument to related methods.

CG: fix tolerance in intersect methods

---

CMakeLists.txt

Experimental feature are disabled by default, whereas deprecated features are enabled by default.
Cmake variables related to experimental and deprecated functions are advanced variables and they will only be visible if the variables BITPIT_SHOW_EXPERIMENTAL or BITPIT_SHOW_DEPRECATED are set to ON.
For each deprecated/experimental feature a corresponding preprocessor macro will be defined. Given the feature FEATURE in the module MODULE, the corresponding preprocessor macro will be called BITPIT_MODULE_FEATURE. The value of the macro will be set to 1 if the feature is enable or it will be set to 0 if the feature is disabled.
Deprecated and experimental should be defined in the section "# Features" of the main CMakeLists.txt

cmake: add functions to define deprecated/experimental features

---

CMakeLists.txt

This allows the compiler to find the header files generated with the cmake command "configure_file".

cmake: search header files also in build directory

---

src/discretization/reconstruction.cpp

Gradients are always defined as arrays with three components, therefore we need to zero unused components when dealing with polynomials defined on lower dimensions.

discretization: explicitly zero unused gradient components

---

src/volcartesian/volcartesian.cpp
src/volcartesian/volcartesian.hpp

Add functions to get vertex coordinates and cell centroid positions along a specified direction.

volcartesian: add functions to get vertex/centroid positions along a direction

---

external/PETSc/cmake/FindPETSc.cmake

Include directories may be specified in the language-specific variables, rather than in the global variable MPI_INCLUDE_PATH.

external: properly add all MPI include directories when running PETSc tests

---

src/IO/VTK.cpp

changed list type for unusedfields tracking because of moving reference issue after possible push_back on m_data std::vector.

VTK::readDataHeader fix disabling of unused fields

---

src/patchkernel/patch_kernel.cpp

Interfaces are now build also on ghost borders.
(Starts from patchkernel.improve.update branch.)

patchkernel: build interface also on ghost borders

---

src/PABLO/LocalTree.cpp
src/PABLO/Octant.cpp
src/PABLO/Octant.hpp
src/PABLO/ParaTree.cpp
src/PABLO/tree_constants.cpp
src/PABLO/tree_constants.hpp

Try to avoid unneeded allocations.

PABLO: optimize refinement

---

src/PABLO/LocalTree.cpp
src/PABLO/LocalTree.hpp
src/PABLO/Octant.cpp
src/PABLO/Octant.hpp
src/PABLO/ParaTree.cpp
test/PABLO/CMakeLists.txt
test/PABLO/test_PABLO_parallel_00005.cpp

Ghost octants there are edge or node neighbours of internal octants were not detected properly on periodic boundaries.
Shuold fix #98.

PABLO: fix evaluation of first layer of ghost on periodic boundaries

---

src/patchkernel/element.cpp
src/patchkernel/patch_kernel_parallel.cpp

There was an error in the identification of the ghost cells during partitioning (the problem was found by code inspection, I don't have a test case that shows the problem).

patchkernel: fix identification of halo cells during partitioning

---

src/levelset/levelSet.cpp
src/levelset/levelSet.hpp
src/levelset/levelSetCommon.hpp
src/levelset/levelSetObject.cpp
src/levelset/levelSetSegmentation.cpp

Even if the distance of a cell is greater than the narrow band size, if that cell intersects the surface, it should be included in the narrow band.

levelset: cells that intersect the surface should always be included in the narrowband

---

src/IO/VTK.cpp

Assert that a valid unused field was found before disabling it (there should be no reasons for the assert to fail, this check is added to silence a Coverity error).

IO/VTK: silence Coverity error when disabling unnused fields

---

src/patchkernel/patch_kernel.cpp

If the containers are replaced, the synchronization of the storages associated with those containers will no longer work.

patchkernel: avoid replacing cell/vertex/interface containers when resetting the patch

---

test/surfunstructured/test_surfunstructured_parallel_00008.cpp

There is no need to partition an empty patch.

test/surfunstructured: remove unneeded patch partitioning

---

.travis.yml
src/PABLO/LocalTree.cpp
src/PABLO/ParaTree.cpp
src/PABLO/ParaTree.hpp
test/PABLO/CMakeLists.txt
test/PABLO/test_PABLO_parallel_00006.cpp

Fixes and improvements to the compact-families partitioning implementation.

PABLO: fix compact-families partitioning implementation

---

src/PABLO/LocalTree.cpp

Zero-check should be performed before decrementing the index.

PABLO: fix identification of last ghost brother in pre-balance algorithm

---

src/IO/index_generator.hpp
src/IO/index_generator.tpp

This changes aim to reduce time spent adding ids into the trash.

IO: optimize handling of index trash in the index generator

---

src/patchkernel/patch_info.cpp

Consecutive numbering is now generated using a sorted vector instead of a map.

patchkernel: optimize extraction of PatchNumberingInfo data

---

src/levelset/levelSetSegmentation.cpp

Due to numerical errors, points that lie on the surface may have a distance slightly grater than zero. Therefore, a small tolerance is now used when checking if a point lies on the segmentation.
Moreover, if a point lies on the segmentation, we assume that it is on the outer side of the surface, this means that the distance is a positive zero and that the gradient is set equal to the surface normal.

levelset: fix evaluation of segment information for points that lie on the segmentation

---

src/common/commonUtils.hpp
src/levelset/levelSetCartesian.cpp
src/levelset/levelSetCartesian.hpp
src/levelset/levelSetKernel.hpp
src/levelset/levelSetObject.cpp
src/levelset/levelSetOctree.cpp
src/levelset/levelSetOctree.hpp

This change allows to get correct results when a cell has a face that lies exactly on an STL border.

levelset: use a tolerance for distance comparisons when evaluating surface intersections

---

src/PABLO/LocalTree.cpp
src/PABLO/LocalTree.hpp
src/PABLO/Octant.cpp
src/PABLO/Octant.hpp
src/PABLO/ParaTree.cpp
src/PABLO/ParaTree.hpp
src/PABLO/morton.hpp
src/voloctree/voloctree.cpp

Instead of storing octant's coordinates, we can store the Morton number. This allows to reduce PABLO memory footprint and speeds up neighbour search.
(This branch starts from PABLO.optimize.find.neighbours.)

PABLO: store Morton number instead of octant's coordinates

---

src/patchkernel/element.cpp
test/volunstructured/test_volunstructured_00001.cpp

There was a bug in the evaluation of local face vertex list for  for polygons and polyhedra.

patchkernel: fix evaluation of face vertex ids for polygons and polyhedra

---

src/patchkernel/element.cpp
src/patchkernel/patch_kernel.cpp
src/patchkernel/patch_kernel.hpp
src/patchkernel/patch_kernel_parallel.cpp
test/volunstructured/test_volunstructured_00001.cpp
test/volunstructured/test_volunstructured_00002.cpp
test/volunstructured/test_volunstructured_parallel_00001.cpp
test/volunstructured/test_volunstructured_parallel_00003.cpp

When automatic indexing is disabled, all ids for newly added cells/vertices/interfaces need to be provided manually. 
Interface auto-indexing cannot be disabled if interfaces build strategy is set to "automatic".

patchkernel: allow to disable automatic cell/vertex/interface auto indexing

---

cmake/BITPITConfig.cmake.in

The file "bitpit_version.hpp" does not exist anymore, let's use "bitpit.hpp" to identify the include directory.

cmake: fix identification of bitpit include directory in CMake configuration file

---

src/PABLO/PabloUniform.cpp
src/PABLO/PabloUniform.hpp
src/PABLO/ParaTree.cpp
src/PABLO/ParaTree.hpp
src/discretization/reconstruction.cpp
src/discretization/reconstruction.hpp
src/levelset/levelSetCartesian.cpp
src/levelset/levelSetCartesian.hpp
src/levelset/levelSetKernel.cpp
src/levelset/levelSetKernel.hpp
src/levelset/levelSetObject.cpp
src/levelset/levelSetOctree.cpp
src/levelset/levelSetOctree.hpp
src/levelset/levelSetSegmentation.cpp
src/patchkernel/patch_skd_tree.cpp
src/patchkernel/patch_skd_tree.hpp
src/patchkernel/surface_skd_tree.cpp
src/volcartesian/volcartesian.cpp
src/volcartesian/volcartesian.hpp

The main optimizations are:
- usage square distance for skd-tree comparisons;
- cache evaluation of cell incircles/circumcircles

levelset: optimizations to levelset computation

---

src/patchkernel/vertex.hpp
src/surfunstructured/surfunstructured.cpp

The algorithm to join the facets was storing the pointers to the vertices of the patch. When new vertices are added, these pointers may get invalidated. Since the container that stores the vertices (PiercedStorage) is based on a std::vector, it is possible to guarantee that the pointers remain valid performing a reserve to the right capacity before starting vertex insertion (this reserve was missing in DGF import). However, there is no official guarantee that the pointers of a PiercedStorage remain valid after adding new elements to the container. The algorithm to identify duplicate vertices is then reworkd and now is not using the pointers to the vertices anymore.

surfunstructured: fix duplicate vertex check

---

README_WINDOWS.md

Simple guide review for README_WINDOWS.md file:
- new msys2/mingw64 core version - 20210419 : lots of changes, since msys guys moved the project to new servers, and compliancy with older versions was a little bit messed up.
- tested bitpit compliancy with the latest petsc version (3.15.0)

Updating guide for MinGW-Win bitpit porting

---

src/containers/piercedKernelIterator.hpp
src/patchkernel/cell.cpp
src/patchkernel/cell.hpp
src/patchkernel/patch_kernel.cpp
src/patchkernel/patch_kernel_parallel.cpp

Optimize update of adjacencies when multiple matches are allowed.

patchkernel: optimize update of adjacencies when multiple matches are allowed

---

src/PABLO/Map.hpp
src/common/commonUtils.hpp

Some includes were missing (see #194).
(The branch "1.7_bitpit.add.missing.includes" contains the same changes for bitpit v1.7.)

Add missing includes

---

CMakeLists.txt
INSTALL.md
README_WINDOWS.md
src/IO/configuration.cpp
src/IO/configuration.hpp
src/IO/configuration_JSON.cpp
src/IO/configuration_JSON.hpp
src/IO/configuration_XML.cpp
src/IO/configuration_XML.hpp
src/IO/configuration_config.hpp
test/IO/CMakeLists.txt
test/IO/data/configuration.json
test/IO/test_IO_00007.cpp

The following pull adds into IO::ConfigParser class the possibility to parse/write json formatted dictionaries. 
Data structure and interfaces of the Config/Config parser classes are the same as before, XML parsing/writing functionalities are also preserved and totally independent from the new json add-on.
RapidJSON external library is used. The external dep is handled silently during bitpit compiling, applying the following the scheme:
1) RapidJSON is found quietly on the system
2) if it's found, set to true a bitpit internal-only precomp variable HAS_RAPIDJSON_LIB and compile with json support.
3) otherwise set to false HAS_RAPIDJSON_LIB, and ignore JSON related code.
In any case, XML support is always guaranteed.
Dictionary format conversion is possible too (parse a JSON file and write …

IO module: add JSON support to configuration package

---

src/voloctree/voloctree.cpp

Mesh update was relying on cell interfaces to identify the vertices that should be deleted. This was unintended and now should be fixed.

voloctree: avoid using cell interfaces during mesh update 

---

src/patchkernel/patch_kernel.cpp
src/voloctree/voloctree.cpp

Moving the declaration of the two vectors outside the for loops we can avoid some allocations.
(The branch "1.7_voloctree.reduce.allocations" contains the same changes for bitpit v1.7.)

voloctree: optimize update of adjacencies

---

src/containers/piercedKernelIterator.hpp
src/containers/piercedStorage.hpp
src/containers/piercedStorageIterator.hpp
src/containers/piercedStorageIterator.tpp
src/containers/proxyVector.cpp
src/containers/proxyVector.hpp
src/containers/proxyVector.tpp
src/discretization/stencil_solver.tpp
src/levelset/levelSetSegmentation.cpp
src/patchkernel/element.cpp
src/patchkernel/patch_info.cpp
src/patchkernel/patch_kernel.cpp
src/patchkernel/patch_kernel_parallel.cpp
src/volcartesian/volcartesian.cpp
src/voloctree/voloctree.cpp
src/voloctree/voloctree_parallel.cpp
test/containers/test_containers_00001.cpp

I've added a very simple "pool allocator" to the ProxyVector container, in order to reduce memory allocations when ProxyVector needs an internal storage. I'm using quotes because what I'm doing is not really a pool allocator, I just save the last 10 internal storages and I re-used those storages when a new ProxyVector is created.

containers: rework handling of ProxyVector internal storage

---

src/patchkernel/patch_kernel.cpp
src/patchkernel/patch_skd_tree.cpp
src/patchkernel/surface_kernel.cpp
src/patchkernel/surface_kernel.hpp

This fixes two kind of errors in vertex ordering:
- connectivity of surface polygons was not reversed correctly;
- vertex of pixel element are not stored in anti-clockwise order but they follow a z-curve order; algorithms of SurfaceKernel that relay on the anti-clockwise ordering need to properly reorder the vertices.
The branch starts from "levelset.normal.evaluation".

patchkernel: fixes to vertex ordering

---

src/patchkernel/patch_skd_tree.cpp
src/patchkernel/patch_skd_tree.hpp
src/patchkernel/surface_skd_tree.cpp

Modify skd-tree to enable thread safe lookups. 
If thread safe lookup is enabled, temporary data structures are allocated at each searching call and used in place of the stack members of the class.

patchkernel: allow to enable thread safe lookups of skdtree

---

src/IO/configuration.cpp

The argument "multiSections" was not used.

IO: fix reset of configuration parser

---

CMakeLists.txt
src/common/bitpit_version.hpp
src/common/version.hpp.in
src/common/version_verbose.hpp.in

Information about git will be added only to the verbose version. This should avoid a whole recompilation every time git data is updated.

cmake: define a verbose version

---

src/levelset/levelSet.cpp
src/levelset/levelSet.hpp
src/levelset/levelSetBoolean.cpp
src/levelset/levelSetBoolean.hpp
src/levelset/levelSetCachedObject.cpp
src/levelset/levelSetCachedObject.hpp
src/levelset/levelSetMask.cpp
src/levelset/levelSetMask.hpp
src/levelset/levelSetMetaObject.cpp
src/levelset/levelSetMetaObject.hpp
src/levelset/levelSetObject.cpp
src/levelset/levelSetObject.hpp
src/levelset/levelSetSegmentation.cpp
src/levelset/levelSetSegmentation.hpp

The current process may only have the portion of the object needed for evaluating the levelset on the cells of its mesh, therefore, when the bounding box of the object is needed, we need to evaluate the overall bounding box across all process.
@edoardolombardi I've also modified the levelset to handle object ids using an IndexGenerator. This should fix the problem you were having when deleting objects from the levelset.

levelset: support distributed objects

---

src/patchkernel/patch_kernel.cpp

method declared in hpp, but missing implementation in cpp.

PatchKernel: fix  missing implementation of getInternalVertexCount method

---

src/discretization/reconstruction.cpp
src/discretization/reconstruction.hpp
src/patchkernel/patch_kernel.cpp
src/patchkernel/patch_kernel.hpp
src/patchkernel/patch_kernel_parallel.cpp
src/patchkernel/surface_kernel.cpp
src/patchkernel/surface_kernel.hpp
src/voloctree/voloctree.cpp
src/voloctree/voloctree.hpp

Voloctree patch now overrides the functions used to identify adjacent faces, this allows to support trees with periodic boundary conditions.

voloctree: override functions to identify adjacent faces

---

src/patchkernel/cell.cpp
src/patchkernel/patch_kernel.cpp
src/patchkernel/patch_kernel.hpp
src/patchkernel/patch_kernel_parallel.cpp

It is not possible to directly transfer a vertex/cell/interface into the storage. First a new element should be created and then that element can be replaced with the source that needs to be transferred into the patch. In order to improve performances, the created element can be just a dummy element, no need to copy its properties from the source.

patchkernel: optimize transfer of vertices/cells/interfaces into the patch

---

src/levelset/levelSet.cpp
src/levelset/levelSetObject.cpp
src/levelset/levelSetSegmentation.cpp

Search radius should be equal to the maximum between the narrow band size and diameter of the circumcircle. This guarantees that, if the size of the narrow band is equal or less than zero, the levelset will be evaluated on the cells that intersect the surface and on all their neighbours.
This is the same behaviour of the octree patch and, as an example, generates the narrow band in the image below.

levelset: fix search radius for Cartesian meshes

---

src/discretization/reconstruction.cpp

Threshold that defines when singular values are discarded is reduced and discarded singular values are now set to zero.
It seems that the code:
```
for (int i = 0; i < k; ++i) {
double sigma_plus = (m_sigma[i] > zeroThreshold) ? (1. / m_sigma[i]) : 0.;
cblas_dscal(m, sigma_plus, &m_U[i*m], 1);
}
```
corresponds to equation 24 of the paper and not to equation 22 (I haven't modified the comment, because I'm not sure if I'm right).
@marcocisternino A threshold of 1e-14 seems quite small, can this threshold be increased to 1e-12?

discretization: modify how singular values are discarded

---

src/levelset/levelSetCachedObject.cpp
src/levelset/levelSetCachedObject.hpp

A cell should be considered external if it is completely outside the object bounding box. If the cell may be intersected by the object (i.e., the bounding box of the cell intersects the bounding box of the object), the cell cannot be flagged as external.

levelset: fix identification of external cells

---

src/containers/piercedKernel.tpp

A "const" keyword was missing.

containers: fix usage of dynamic cast

---

src/LA/system_solvers_large.cpp
src/LA/system_solvers_large.hpp

When the solution of the system is the null vector, it may be necessary to impose an absolute tolerance to get a properly convergence of the solver.

Add absolute convergence threshold to KSP options

---

src/patchkernel/patch_info.cpp

This fixes the identification of cell rank from global/consecutive id.

patchkernel: fix cell rank from consecutive id getter

---

src/levelset/levelSetObject.cpp
src/levelset/levelSetObject.hpp

To have more descriptive field names, the following patter is now used for generating the VTK names: ``` levelset<FIELD_TYPE>_<OBJECT_NAME>```.

levelset: use more descriptive names for VTK fields

---

src/containers/proxyVector.cpp
src/containers/proxyVector.hpp
src/containers/proxyVector.tpp
src/levelset/levelSetObject.cpp
src/levelset/levelSetObject.hpp

It is now possible to create a thread-safe ProxyVector.

containers: define a thread-safe version of the ProxyVector

---

src/patchkernel/patch_skd_tree.cpp
src/patchkernel/patch_skd_tree.hpp
src/patchkernel/surface_skd_tree.cpp

When performing searches with the SkdTree, empty partitions may lead to floating point exceptions. Also, a floating point exception may be triggered when evaluating the square of an "inifinite" distance (i.e., a distance set to ```std::numeric_limits<double>::max()```).

patchkernel: avoid floating point exceptions in SkdTree class

---

INSTALL.md
cmake/BITPITConfig.cmake.in

When bitpit is used as dependency library, BITPIT_CMAKE_CONFIG_PATH_LAST chached internal variable wasn't declared properly. This triggered the reconfigure procedure every time.

cmake: fix definition of BITPIT_CMAKE_CONFIG_PATH_LAST variable in BITPITConfig.cmake.in

---

src/patchkernel/element.cpp

FIx to get the correct binary size of non standard Cell Elements  (like polyhedra)

patchkernel: fix Element::getBinarySize method

---

src/containers/piercedStorage.tpp
src/containers/piercedSync.cpp
src/containers/piercedSync.hpp

Merging the sync actions allows to reduce the time spent in commitSyncAction.

containers: merge sync actions when adding them to the journal

---

src/patchkernel/patch_kernel.cpp

The implementation of the methods internalVertexConst*  were missing.

patchkernel: add missing implementation of internalVertexConst* methods

---

src/RBF/rbf.cpp

I'm not sure this is the right fix, but weights were erased using values' iteratror . Found by cppcheck.
Other than the fix for data set removal, there are some cosmetic fixes.

RBF: fix data set removal

---

src/patchkernel/patch_kernel.cpp

The implementation of the function was missing.

patchkernel: add missing implementation of getLastInternalVertex methods

---

src/patchkernel/patch_kernel.hpp
src/patchkernel/patch_kernel_parallel.cpp

There is no need to build partitioning information is the patch is on one single processor.

patchkernel: avoid building partitioning information when the patch is on one processor

---

src/discretization/reconstruction.cpp

Polynomials of degree 0 and 1 are supported on all type of cells, for pixels and voxels also degree 3 is supported.
Note: coefficients are evaluated as the volume average of the Taylor series expansion coefficients. In order to support higher order degrees on all type of cells, we will need to implement numerical integration of the expansions terms over the volume of the cell. This can be done using Gauss quadrature rules and evaluating the terms on the integration points using the function that evaluate the basis function on a specified point.

discretization: low order cell basis can be evaluated on all type of cells

---

src/PABLO/tree_constants.cpp
src/PABLO/tree_constants.hpp

The constant MAX_LEVEL defines the maximum allowed level, hence tree constants need to be evaluated also for this level.

PABLO: fix evaluation of tree constants

---

src/containers/flatVector2D.hpp
src/containers/flatVector2D.tpp
src/patchkernel/cell.cpp
src/patchkernel/cell.hpp
src/patchkernel/patch_info.cpp
src/patchkernel/patch_kernel.cpp
src/patchkernel/patch_kernel.hpp
src/patchkernel/patch_kernel_parallel.cpp
src/voloctree/voloctree.cpp

When destroying adjacencies/interfaces their memory should be released.
Note: in terms of memory, the difference between resetting and deleting interfaces/adjacencies is just 4+4 bytes per cell.

patchkernel: properly release memory when destroying the adjacencies/interfaces

---

src/patchkernel/element.cpp
src/patchkernel/element.hpp

Improve the documentation of Element::setId and Element::setPID methods.

patchkernel: fix Doxygen documentation

---

src/LA/system_matrix.cpp
src/LA/system_matrix.hpp
src/LA/system_solvers_large.cpp
src/LA/system_solvers_large.hpp
src/discretization/stencil_solver.hpp
src/discretization/stencil_solver.tpp
test/integration_tests/LA/CMakeLists.txt
test/integration_tests/LA/test_LA_00002.cpp
test/integration_tests/LA/test_LA_00003.cpp
test/integration_tests/LA/test_LA_parallel_00001.cpp
test/integration_tests/LA/test_LA_parallel_00002.cpp

Added a function to evaluate the transpose of a sparse matrix.

LA: allow to solve the transpose of a sparse system

---

src/levelset/levelSet.cpp
src/levelset/levelSetSignPropagator.cpp
src/levelset/levelSetSignedObject.cpp

When restoring LevelSetSignedObjectInterface, the sign storage needs to be explicitly initialized.

levelset: fix restore of sign storage

---

src/IO/index_generator.tpp
src/patchkernel/patch_kernel.cpp
src/patchkernel/patch_kernel.hpp

Index generators were not properly restored when auto indexing was set to false.

patchkernel: fix dump/restore of index generators

---

src/common/logger.cpp
src/common/logger.hpp

The logger buffer was not properly copied.

Fix copy constructor of the logger

---

src/LA/matrix_utilities.tpp
src/LA/system_solvers_small.cpp
src/LA/system_solvers_small.hpp

Two commits are in this branch.
The first one introduces two new solveLU functions (one for solution only, the other one for solution and factorization). The number of rhs is limited to 1. Two extern constant have been introduced to set the matrix layout using lapack values and to avoid application to include lapacke headers.
The second commit fix the determinant evaluation by fixing the complement build and by calling the complement function with opportune arguments.

Add lapacke-based solveLU

---

src/levelset/levelSetSignPropagator.cpp

Sign propagator should get the levelset sign from the sign storage.

levelset: fix assert condition

---

src/containers/piercedKernel.cpp
src/containers/piercedKernel.hpp
src/containers/piercedStorage.hpp
src/containers/piercedStorage.tpp
src/containers/piercedVector.tpp
src/containers/piercedVectorStorage.cpp
src/containers/piercedVectorStorage.hpp
test/integration_tests/containers/CMakeLists.txt
test/integration_tests/containers/test_containers_00001.cpp
test/integration_tests/containers/test_containers_00002.cpp
test/integration_tests/containers/test_containers_00003.cpp

Some contents of the PiercedVector were copied instead of being moved.

containers: fix PiercedVector move

---

src/lineunstructured/CMakeLists.txt
src/pointcloud/CMakeLists.txt

CMake minimum required version for the pointcloud and lineunstructured module was erroneously set to 2.8. Minimum required version should be 3.10.

cmake: bump pointcloud and lineunstructured cmake minimum required version to 3.10

---

src/surfunstructured/surfunstructured.cpp

The number of facets and the number of vertices of a triangulation are related by the inequality nFacets <= 2 * nVertices - 4, where the equality holds for a closed triangulation. To limit memory usage in the case the facets are joined, we estimate the number of vertices assuming a closed triangulation (this gives us the minimum number of nodes the triangulation could possibly have).
With this change, there is a 30% reduction in the memory needed for importing a closed triangulation of 500K elements.

surfunstructured: use a better estimate of the number of vertices when importing an STL

---

src/patchkernel/patch_kernel.hpp
src/patchkernel/patch_kernel_parallel.cpp

The functions isDistributed and getOwner can now be called also when the patch is not up-to-date (the argument allowDirty should be set to true). If dirty patches are allowed and the patch is actually dirty, the functions will evaluate the owner on-the-fly. Otherwise the functions will use the owner evaluated during the last update. In any case, if dirt patches are allowed, the function is a collective function and needs to be called by all processes (otherwise a deadlock will occur).

patchkernel: allow evaluating patch owner also when patch is dirty

---

src/patchkernel/patch_kernel_parallel.cpp

The assert in Patchkernel::getOwner was wrong, additionally partitioning information status should be tracked also when there is only one processor.
Close #311

patchkernel: fix evaluation of partitioning information

---

CMakeLists.txt

The new build type "RelWithSanitize" enables the support for AddressSanitizer. Active modules are "undefined" and "address".

cmake: add support for AddressSanitizer

---

src/levelset/levelSetSignPropagator.cpp

Ghost cells are not tracked by adaption, we need to explicitly initialize the sign on all ghost cells.

levelset: properly initialize sign on ghost cells after adaption

---

src/patchkernel/patch_kernel.cpp
src/patchkernel/patch_kernel_parallel.cpp

If no adjacencies/interfaces are build, there is no need to set the associated alteration flag. Since alteration flags are stored in an unordered_map, this will improve PatchKernel memory usage when no adjacencies/interfaces are needed.

patchkernel: set alteration flags only when needed

---

src/patchkernel/patch_skd_tree.cpp
src/patchkernel/patch_skd_tree.hpp

Cell centroids were only used to detect element ordering. For this purpose, the centroid of the element's bounding box can be used.
In order to recover the performances lost due to the computation of the cell bounding box centroid, I've also optimized the generation of the Skd-Tree. The splitting between left and right elements can be done evaluating only the position of the element along the direction of the splitting rather than evaluating the whole bounding box of the element.

patchkernel: reduce memory usage of Skd-Tree cache

---

src/patchkernel/patch_kernel.cpp
src/patchkernel/patch_kernel.hpp
src/patchkernel/patch_kernel.tpp
src/voloctree/voloctree.cpp

This avoid creating a list of vertices to delete during the adaption of the VolOctree patch.

patchkernel: allow to pass a generic container to the functions that delete cells/vertices/interfaces

---

src/levelset/levelSetSignPropagator.cpp

We need at least one seed to be able to perform sign propagation (i.e., at least one cell should be in the levelset narrowband).

levelset: check if there are seeds to be used for sign propagation

---

src/containers/piercedStorage.tpp

The [] operator of std::vector<bool> returns a temporary object of a proxy type called std::vector<bool>::reference, rather than an actual bool&.
Although the libstdc++ defines an overload for swapping this type of proxy objects, this is just an extension to the standard.
Without this change bitpit doesn't compile with gcc 12.

containers: fix swap for PiercedStorage<bool>

---

src/levelset/levelSetSignPropagator.cpp

Throwing an exception when there are no seed is wrong if sign propagation is not needed.

levelset: having no seeds is fine if no sign propagation is needed

---

src/PABLO/Map.cpp
src/PABLO/Octant.cpp
src/PABLO/PabloUniform.cpp
src/PABLO/ParaTree.cpp
src/PABLO/ParaTree.hpp

They all seem false positive, with the exception for the initialization of the global number of octants.

PABLO: silence some "uninitialized variable" warnings reported by Coverity

---

src/patchkernel/patch_kernel.cpp
src/patchkernel/patch_kernel.hpp
src/patchkernel/patch_kernel_parallel.cpp

There is now a function to initialize a dummy communicator when MPI support is disabled.

patchkernel: consolidate initialization of the communicator

---

src/PABLO/Octant.cpp
src/PABLO/Octant.hpp
src/common/logger.cpp
src/common/logger.hpp
src/communications/communications_buffers.hpp
src/communications/communications_buffers.tpp
src/containers/binary_stream.cpp
src/containers/binary_stream.hpp
src/containers/binary_stream.tpp
src/containers/flatVector2D.hpp
src/containers/flatVector2D.tpp
src/discretization/stencil.hpp
src/discretization/stencil.tpp
src/operators/Operators.hpp
src/operators/Operators_array.tpp
src/operators/Operators_vector.tpp
src/patchkernel/cell.cpp
src/patchkernel/cell.hpp
src/patchkernel/element.cpp
src/patchkernel/element.hpp
src/patchkernel/vertex.cpp
src/patchkernel/vertex.hpp
src/voloctree/voloctree.cpp

In release mode, VolOctree patch will display PABLO messages only when their severity is WARNING or higher.
To achieve this I had to rework a bit the logger: loggers that were sharing the same buffer were sharing also the visibility settings, but this was not the intended behaviour. Other than fixing this problem, the reworked logger should be faster.

voloctree: reduce visibitiy of PABLO messages

---

src/discretization/stencil_solver.tpp

The problem has been identified by GCC 12.

discretization: properly cast assembler to be used for stencil solver update

---

src/IO/DGF.cpp

Fixes the following GCC warning:
In constructor ‘std::fpos<_StateT>::fpos(std::streamoff) [with _StateT = __mbstate_t]’,
inlined from ‘unsigned int bitpit::dgf::checkData(std::ifstream&, int&)’ at /home/andrea/work/customers/optimad/present/20150716_bitpit/code/src/IO/DGF.cpp:1142:22:
/usr/include/c++/12/bits/postypes.h:104:9: warning: ‘current_pos’ may be used uninitialized [-Wmaybe-uninitialized]
104 |       : _M_off(__off), _M_state() { }
|         ^~~~~~~~~~~~~
/code/src/IO/DGF.cpp: In function ‘unsigned int bitpit::dgf::checkData(std::ifstream&, int&)’:
/code/src/IO/DGF.cpp:1100:17: note: ‘current_pos’ was declared here
1100 | long int        current_pos;
|                 ^~~~~~~~~~~

IO/DGF: make sure the current position in the file is properly initialized

---

src/LA/system_solvers_large.hpp
src/PABLO/LocalTree.hpp
src/RBF/rbf.cpp
src/RBF/rbf.hpp
src/containers/piercedStorageIterator.hpp
src/containers/piercedSync.hpp
src/levelset/levelSetBoundedObject.hpp
src/levelset/levelSetCachedObject.hpp
src/levelset/levelSetMaskObject.hpp
src/levelset/levelSetObject.hpp
src/levelset/levelSetSegmentationObject.hpp
src/patchkernel/volume_mapper.hpp

I've removed some unused headers and replaced others with forward declarations (this changes have been suggested by cppclean).

Optimize header inclusion

---

src/patchkernel/element_reference.cpp
src/patchkernel/interface.cpp
src/patchkernel/surface_kernel.hpp

They all seem false positive, with the exception for the initialization of ReferenceElementInfo::edgeConnectStorag.

patchkernel: silence some "uninitialized variable" warnings reported by Coverity

---

src/levelset/levelSetCachedObject.cpp
src/levelset/levelSetSegmentationObject.cpp
src/voloctree/voloctree.cpp

The algorithm used for updating the narrow band adds the cell to the cache and immediately after it evaluates cache information. In this case using a concurrent synchronization for the PiercedStorages is faster than using a journaled synchronization.

levelset: change synchronization method of narrowband cache 

---

src/containers/piercedStorage.hpp
src/containers/piercedStorage.tpp

When no alternative kernel is provided, use the kernel of the object being copied/moved.

containers: fix PiercedStorage copy/move constructors

---

src/common/compiler.hpp

Added new macro to define functions as deprecated with message as input argument.
With this new macros BITPIT_DEPRECATED_FOR (one for each supported compiler as the original ones) is possibile to pass a message to indicate wich method has to be used instead.
Currently compiled and tested only for GNUC case.

common: add message to deprecated macros

---

src/patchkernel/patch_kernel.cpp
src/patchkernel/patch_kernel.hpp

The bug was found and fixed by @DMurataj01, this is just a slightly modified version of #305. 
@DMurataj01 Can you please check if this pull request fixes the problem?

patchkernel: reset index generators after renumbering cells/vertices/interfaces

---

src/common/logger.cpp

The string where the timesamp was build was too small.

common: fix timestamp displayed by the logger

---

external/clang-format/cmake/ClangFormat.cmake
src/CMakeLists.txt
test/CMakeLists.txt

We need to check if clang-format executable has been found before using it.

cmake: fix compilation when clang-format is not available

---

src/patchkernel/patch_info.cpp
src/patchkernel/patch_info.hpp
src/patchkernel/patch_kernel.cpp
src/patchkernel/patch_kernel.hpp
src/patchkernel/patch_kernel.tpp
src/patchkernel/patch_kernel_parallel.cpp
src/patchkernel/patch_kernel_parallel.tpp
src/patchkernel/surface_skd_tree.cpp
src/surfunstructured/surfunstructured.cpp
src/surfunstructured/surfunstructured.hpp
src/voloctree/voloctree.cpp
src/voloctree/voloctree.hpp
src/voloctree/voloctree_parallel.cpp
src/volunstructured/volunstructured.cpp
src/volunstructured/volunstructured.hpp
test/integration_tests/surfunstructured/test_surfunstructured_parallel_00008.cpp
test/integration_tests/volunstructured/test_volunstructured_parallel_00001.cpp
test/integration_tests/volunstructured/test_volunstructured_parallel_00002.cpp

It is now possible to build more than one layer of ghost cells.
Draft because it needs more testing.

patchkernel: allow to build more than one layer of ghost cells

---

src/volunstructured/volunstructured.cpp
src/volunstructured/volunstructured.hpp
test/integration_tests/volunstructured/CMakeLists.txt
test/integration_tests/volunstructured/test_volunstructured_parallel_00005.cpp

This PR changes the way the halo size is set. 
Now it is possible to set the halo size only if the patch is all on a single process. 
The function _getMaxHaloSize is overridden also for volunstructured, in this way it is possible to set more the one layer of ghost also for this patch.

volunstructured: enable generation of multiple halo layers 

---

src/common/compiler.hpp
src/common/logger.cpp

Fixed a couple of minor bugs that raises errors during msvc compilation.
- unsupported uint fixed with unsigned int
- fixed wrong expansion of BITPIT_DEPRECATED_FOR in MSC_VER case

common: msvc porting miscellaneous fixes

---

src/PABLO/ParaTree.cpp

Fixes an error when compiling bitpit with libc++ (resolves #348).

PABLO: explicitly cast bitset::reference to bool

---

external/git/cmake/GetGitRevisionDescription.cmake

The main issue was that the function get_git_head_revision was calling find_package(Git).

cmake: properly search for git application before using it

---

src/common/logger.hpp

The "complier.hpp" header was missing.

common: add missing header inclusion

---

src/CG/CG_elem.cpp

So far, this took place by creating triangles with the 1st vertex of the polygon and two other vertices of the polygon. In case these 3 vertices are collinear, the debug mode does not complete its execution. Now, the approximate barycenter of the polygon is computed and is used along with two vertices of the polygon to create the triangles.
Closes #355

CG: fix in the triangulation of a polygon

---

src/LA/system_solvers_large.cpp

If the sizes of PETSc data types match the sizes of data types used by bitpit a direct update can be performed, otherwise the matrix is updated using intermediate data storages.

LA: optimize update of system matrix

---

CMakeLists.txt
src/levelset/levelSetUnstructuredKernel.hpp
src/voloctree/voloctree_mapper.hpp

Warn about overriding virtual functions that are not marked with the override keyword.

cmake: add a compiler flag to warn about missing override keywords

---

external/git/cmake/GetGitRevisionDescription.cmake

This allows to properly support directory with spaces.
Fixes #357.

external/git: quote argument passed to function

---

src/discretization/reconstruction.cpp
src/discretization/reconstruction.hpp

It is possible to optimize the evaluation of constant polynomials taking advantage of the fact that basis value is 1 and basis derivative is 0. 
This kind of optimization was already done for the evaluation of the polynomial value and gradient. Let's extend it also for the update of the polynomials and for the evaluation of the weights.

discretization: add some fast paths for constant polynomials

---

src/LA/system_solvers_large.cpp
src/LA/system_solvers_large.hpp
src/common/commonUtils.hpp
src/common/commonUtils.tpp
src/discretization/stencil_solver.hpp
src/discretization/stencil_solver.tpp

The fast path will use the PETSc function MatSetValuesRow to update all the values of a row at once (without the need to get the row pattern).
Fast update can be performed if:
- the matrix has already been assembled;
- the assembler is providing all the values of the row;
- values provided by the assembler are sorted by ascending column.

LA: add a fast path for updating matrix values

---

src/discretization/reconstruction.cpp

The current storage size was not properly evaluated.
I've also updated the function that evaluates the polynomial coefficients: since the weight matrix is usually small, it's faster perform matrix vector multiplication using an ad-hoc code rather than using CBLAS functions..

 discretization: fix logic to detect if polynomial storage should be resized

---

src/PABLO/ParaTree.cpp
src/PABLO/ParaTree.hpp
src/voloctree/voloctree_mapper.cpp
src/voloctree/voloctree_parallel.cpp

The container passed to the function that performs the initial load balance was not the container with the correct weights.

voloctree: fix partitioning initialization

---

src/levelset/levelSetProxyObject.cpp

If the reference object we get is not a primary object, we need to recursively find the primary object associated with it.

levelset: fix identification of primary object associated with proxies

---

src/patchkernel/element.cpp
src/patchkernel/element.hpp
src/patchkernel/patch_kernel.cpp

When coincident vertices are collapsed, interfaces and adjacencies need to be updated accordingly.

patchkernel: fix collapse of coincident vertices

---

src/IO/STL.cpp
src/patchkernel/element_reference.cpp

The formula for evaluating the volume needs the position of four vertices that identifies the x, y, and z edges.

patchkernel: fix evaluation of voxel volume

---

src/patchkernel/element.cpp

The return vector must be normalized to assure to be a versor.

patchkernel: fix evaluation of normal for polygonal elements

---

src/IO/VTKUnstructured.cpp
src/patchkernel/patch_kernel.cpp

In 3D meshes, if at least one element without info (POLYGONS, POLYHEDRA) is present even in just one mesh partitions, all the ranks must write VTK DataArrays offset, types, connectivity, faces and faceoffsets in their own vtu file. Otherwise, single vtu files are readable but the pvtu file is not.

patchkernel: fix VTK parallel output

---

src/IO/VTKUnstructured.cpp

It seems that pvtu files should contain a PCells section. I wasn't able to find any documentation about which sections are required in those files. What I did, was adding a PCells section with a list of cell-related arrays that will be contained in the vtu files associated with the collection. 
I'm not able to properly test the changes, because ParaView is able to open the pvtu files generated by bitpit even without these changes.

IO: add missing PCells section in VTK parallel files

---

src/levelset/levelSetSegmentationObject.cpp
src/patchkernel/element.tpp
src/patchkernel/surface_kernel.cpp
src/patchkernel/surface_kernel.hpp

Connectivity of pixel elements does not list the vertices in anti-clockwise order. This needs to be properly taken into account when flipping the normal and when evaluating segment information.

levelset: fix evaluation of levelset for surfaces that contain pixel elements

---

test/integration_tests/volunstructured/test_volunstructured_parallel_00001.cpp
test/integration_tests/volunstructured/test_volunstructured_parallel_00002.cpp
test/integration_tests/volunstructured/test_volunstructured_parallel_00005.cpp

Fix VolUnstructured tests for MPICH implementation.
When using MPICH as MPI implementation the MPI_Comm is a typedef of integer.
The overloaded constructors of VolUnstrunctured are ambiguous when the argument are not explicitly casted.

test: fix volunstructured tests

---

src/LA/system_solvers_large.cpp
src/LA/system_solvers_large.hpp

System Solver 's assembly methods have been fixed to build without MPI

LA: fixes for serial builds

---

src/CG/CG_elem.cpp
src/levelset/levelSetSegmentationObject.cpp
src/levelset/levelSetSegmentationObject.tpp

Levelset sign should be evaluated with the same tolerance used when checking if the point lies on the segmentation. Also, I've replace the algorithm for projection points onto triangles. The new algorithm is more precise when the point lies on the triangle.

levelset: fix evalution of segment information for points that lie on the segmentation

---

src/levelset/levelSetSegmentationObject.cpp
src/levelset/levelSetSegmentationObject.tpp
src/patchkernel/element.tpp
src/patchkernel/element_reference.cpp
src/patchkernel/element_reference.hpp
src/patchkernel/surface_kernel.cpp
src/patchkernel/surface_kernel.hpp
src/patchkernel/volume_kernel.cpp
src/patchkernel/volume_kernel.hpp

There were still some cases where the pixel's vertices were not properly ordered before passing them to the CG utilities.
Depends on #394.

levelset: fix evaluation of levelset on segmentation with pixel elements

---

examples/RBF_example_00001.cpp

RBF example was not compiling without MPI support enabled.

examples: fixes for serial builds

---

src/IO/STL.cpp

The space after the keyword "solid" is not a hard requirement of the [format](https://en.wikipedia.org/wiki/STL_(file_format)), it's only needed by some programs.

IO: do not require a space after the "solid" keyword of STL ASCII files

---

src/discretization/reconstruction.cpp

Function "computeDerivatives" evaluates the gradient along the given normal direction similarly to function "computeGradients". However, when dimensions are zero, computeDerivatives throws a segmentation error, while computeGradients returns a zero value. This pull-request modifies computeDerivatives to be in accordance with computeGradients.

reconstruction: correct the computation of derivatives

---

src/IO/binary_archive.cpp

The header should be written using the write overload that takes in input characters, because the one that takes in input strings would write into the archive also the string length.

IO: fix writing of binary archive header

---

src/patchkernel/patch_skd_tree.cpp
src/patchkernel/patch_skd_tree.hpp

Having public constructors allows to get rid of the custom allocator.

patchkernel: declare SkdNode constructors as public

---

src/levelset/levelSetMaskObject.tpp
src/levelset/levelSetSegmentationObject.cpp
src/levelset/levelSetSegmentationObject.hpp
src/levelset/levelSetSegmentationObject.tpp

Instead of storing the segmentation kernel in a member, let's just derive from it.
Depends on #376.

levelset: derive segmentation objects from the corresponding kernel

---

src/IO/VTK.cpp
src/IO/VTK.hpp
src/IO/VTK.tpp
src/IO/VTKField.cpp
src/IO/VTKRectilinear.cpp
src/IO/VTKUnstructured.cpp
src/IO/VTKUtils.cpp
test/integration_tests/IO/test_IO_00001.cpp

Second-order tensors should be passed to the VTK classes as 9-component vectors. It's up to the user of the VTK classes
to specify how the tensors are linearized (e.g., row-major order).

IO/VTK: add support for second-order tensor fields

---

examples/voloctree_adaptation_example_00001.cpp
src/IO/VTK.cpp
src/IO/VTK.hpp
src/IO/VTKRectilinear.cpp
src/IO/VTKStreamer.tpp
src/IO/VTKUnstructured.cpp
src/levelset/levelSetObject.cpp
src/patchkernel/patch_kernel.cpp

The new function allows to easily flush values on both ASCII and appended files.

IO: add a generic function to flush VTK values 

---

examples/voloctree_mapper_example_00003.cpp
examples/voloctree_mapper_example_00004.cpp
src/POD/pod.cpp
src/POD/pod_common.hpp
src/POD/pod_kernel.cpp
src/POD/pod_voloctree.cpp
src/containers/piercedStorage.hpp
src/containers/piercedStorage.tpp
src/containers/piercedSync.cpp
src/containers/piercedSync.hpp
src/containers/piercedVector.tpp
src/containers/piercedVectorStorage.hpp
src/containers/piercedVectorStorage.tpp
src/levelset/levelSet.cpp
src/levelset/levelSetObject.cpp
src/levelset/levelSetSegmentationObject.cpp
src/levelset/levelSetSignPropagator.cpp
src/patchkernel/patch_kernel.cpp
src/patchkernel/volume_mapper.cpp
src/patchkernel/volume_mapper.hpp
src/voloctree/voloctree_mapper.cpp
src/voloctree/voloctree_mapper.hpp
test/integration_tests/containers/test_containers_00003.cpp
test/integration_tests/voloctree/test_voloctree_00004.cpp
test/integration_tests/volunstructured/test_volunstructured_00002.cpp
test/integration_tests/volunstructured/test_volunstructured_parallel_00001.cpp

The rationale for this change is that when a storage is registered for synchronization, it won't alter the kernel in a way that affects the usage of the kernel. What happens is that a new PiercedSyncSlave will be added to the list of objects that should be keep in sync with the kernel.

containers: allow to pass a constant kernel when setting dynamic synchronization of a PiercedStorage

---

src/LA/system_matrix.cpp
src/LA/system_matrix.hpp
src/LA/system_solvers_large.cpp
src/LA/system_solvers_large.hpp

From the PETSc user manual: "To solve successive linear systems that have different preconditioner matrices (i.e., the matrix elements and/or the matrix data structure change), the user must call KSPSetOperators() and KSPSolve() for each solve."

LA: properly setup the preconditioner when solving multiple linear systems

---

src/containers/piercedKernel.tpp
test/integration_tests/containers/test_containers_00001.cpp
test/integration_tests/containers/test_containers_00002.cpp
test/integration_tests/containers/test_containers_00003.cpp

When a hole is created the setPosEmptyId made the m_ids vector non-coherent.
This solution is the simplest one, but the less efficient one when the kernel has to be iterated.
This solution solved issues in application using piercedKernel

containers: fix function to set the id of an empty positions of a PiercedKernel

---

src/IO/VTK.hpp
src/IO/VTKStreamer.tpp

Functions that flush values to a stream can be declared as constant.

IO/VTK: declare some functions as constants

---

src/patchkernel/patch_kernel.cpp
src/voloctree/voloctree.cpp
src/voloctree/voloctree.hpp

It is faster to evaluate the bounding box in PatchKernel rather than delegate the evaluation to PABLO.

patchkernel: optimize evaluation of vertex/pixel/voxel bounding box

---

src/discretization/stencil.hpp
src/discretization/stencil.tpp

Passing a functor is more general than passing a map.

discretization: allow renumber the stencils using a functor

---

src/levelset/levelSetSegmentationObject.cpp

The validity flag should be explicitly set to false, otherwise, if the surface is set multiple times, the container may contain elements wrongly set to true (they were set to true during the evaluation of the levelset with the previous surface).

levelset: fix initialization of segmentation limited-normal validity flag

---

src/patchkernel/surface_kernel.cpp
src/patchkernel/surface_kernel.hpp
test/integration_tests/surfunstructured/test_surfunstructured_parallel_00003.cpp

The function can be used to check if all the factes of a surface patch are oriented in the same way. 
Draft because it need more testing.

 patchkernel: add a function to check if factes of surface patch have a consistent orientation

---

src/PABLO/LocalTree.cpp
src/PABLO/LocalTree.hpp
src/PABLO/ParaTree.cpp
src/PABLO/ParaTree.hpp

Before starting balancing a partitioned tree, it is necessary to exchange the adaption markers.

PABLO: fix parallel 2:1 balance

---

src/LA/system_matrix.cpp
src/LA/system_matrix.hpp
test/integration_tests/LA/test_LA_parallel_00001.cpp
test/integration_tests/LA/test_LA_parallel_00002.cpp

This is an example of the information that will be displayed:
```
General information
Block size ............................................ 5
Local information: 
Maximum number of non-zero blocks per row ............. 25
Maximum number of non-zero elements per row ........... 125
Number of block rows .................................. 1296
Number of block columns ............................... 1296
Number of non-zero blocks (pattern) ................... 28781
Number of non-zero elements (pattern) ................. 719525
Number of non-zero blocks (non-neglibile values) ...... 28737
Number of non-zero elements (non-neglibile values) .... 393235
Sparsity of the blocks (pattern) ...................... 0.982865
Sparsity of the elements (pattern) .................... 0.982865
Sparsity of …
```

LA: add a function to display information about a sparse matrix

---

src/IO/configuration_XML.cpp

Nowadays UTF-8 is the default encoding for almost every application.

IO: change the defualt encoding of the XML config to "UTF-8"

---

src/CG/CG.hpp
src/CG/CG_elem.cpp
test/integration_tests/CG/test_CG_00001.cpp
test/integration_tests/CG/test_CG_00002.cpp

This pull request:
1. adds a new function for evaluating the point-line intersection
2. improves the test checking the point-segment intersection
3. micro-optimizes the function evaluating the point-segment intersection (there is one less square root).
This pull-request completes task [IMM-728](https://optimad.youtrack.cloud/issue/IMM-728).

CG/CG_elem: rework point/plane intersection evaluation

---

src/containers/piercedStorage.tpp
src/containers/piercedSync.cpp
src/containers/piercedSync.hpp

Consecutive overwrite actions can be merged together.

containers: merge pierced synchronization actions of type overwrite

---

src/containers/piercedStorage.hpp
src/containers/piercedSync.cpp
src/containers/piercedSync.hpp
src/containers/piercedVector.hpp
src/containers/piercedVector.tpp

Dump/restore are now enabled also for PiercedVectors that store POD data (previously they were enabled only if the data was implementing dump/restore functions).
PiercedSyncActions with no data are now properly dumped/restored (this change breaks the compatibility with older dumps).

containers: fixes and improvements to the restore of PiercedVector containers

---

src/RBF/rbf.cpp

The pull fixes the construction of the matrix of the system solved during interpolation by RBFs (for both full problem and greedy algorithm). 
In case of variable support radii of the RBFs the matrices were filled in the wrong order producing incorrect results. 
Tiny fix to avoid redefinition of local variables inside functions is also introduced during the fixing.

RBF: fix matrix definition in solve and solveLSQ methods

---

src/containers/piercedStorage.hpp
src/containers/piercedStorage.tpp

The generic function was triggering a compiler warnings because using the move operator on a temporary object (i.e., on std::vector<bool>::reference) prevents copy elision.

containers: add a dedicated function to swap boolean values stored in a PiercedStorage

---

src/common/commonUtils.cpp
src/common/commonUtils.hpp
src/discretization/reconstruction.cpp
src/discretization/reconstruction.hpp

There are cases in which weights should be evaluated using the coefficients associated with only some of the equations.

discretization: allow to evaluate partial reconstruction weights

---

.github/workflows/continuous_integration.yml
.travis.yml
environments/ubuntu/Dockerfile

Continuous integration is now handled by github actions and runs on non-cloud machines (Ubuntu 20.4).
CI works in the same way as before, there are just some differences in the tests being run (we don't test anymore the compilation using older gcc versions).
The results of the tests are available at the follwing link: "https://github.com/optimad/bitpit/actions/workflows/continuous_integration.yml". Here an example of how the test results look like:

cicd: add github configuration to run continuous integration

---

src/levelset/levelSet.cpp
src/levelset/levelSetCachedObject.cpp
src/levelset/levelSetCachedObject.hpp
src/levelset/levelSetCachedObject.tpp
src/levelset/levelSetObject.cpp
src/levelset/levelSetObject.hpp
src/levelset/levelSetSegmentationObject.cpp
src/levelset/levelSetSegmentationObject.hpp
src/levelset/levelSetSegmentationObject.tpp
src/levelset/levelSetSignPropagator.cpp
src/levelset/levelSetSignedObject.cpp
src/levelset/levelSetStorage.cpp
src/levelset/levelSetStorage.hpp
src/levelset/levelSetStorage.tpp

Objects that use a storage with automatic synchronization cannot exchange the levelset values after a partitioning, but need to evaluate the levelset on the received cells. That's because, at the time the update takes place, the automatic synchronization has already deleted the data of the cells that have been sent.

levelset: fix object update after partitioning

---

src/IO/VTK.cpp
src/IO/VTK.hpp
src/IO/VTKRectilinear.cpp
src/IO/VTKUnstructured.cpp
src/IO/configuration_XML.cpp
src/common/fileHandler.cpp
src/common/fileHandler.hpp
src/patchkernel/patch_kernel.cpp
src/patchkernel/patch_kernel.hpp

The VTK class is now able to write [PVD files](https://vtk.org/Wiki/ParaView/Data_formats#PVD_File_Format) containing the  information about the time series.

IO/VTK: add support for writing time series 

---

src/POD/pod.cpp

The pull request fixes an issue with the pod kernel clearMapper method. Previous implementation caused runtime error when pod objects were instantiated without setting the pod kernel. The current modification prevents this from happening.

POD: fix pod kernel clear

---

src/common/fileHandler.cpp

Fixes the following warning:
```
In file included from /opt/bitpit/src/common/bitpit_common.hpp:45,
from /opt/bitpit/src/common/fileHandler.cpp:30:
/opt/bitpit/src/common/fileHandler.hpp: In constructor 'bitpit::FileHandler::FileHandler()': /opt/bitpit/src/common/fileHandler.hpp:55:31: warning: 'bitpit::FileHandler::parallel' will be initialized after [-Wreorder]
55 |         bool                  parallel ;       /**< is part of distributed data? */
|                               ^~~~~~~~
/opt/bitpit/src/common/fileHandler.hpp:53:31: warning:   'int bitpit::FileHandler::counter' [-Wreorder]
53 |         int                   counter ;        /**< counter for time series ; */
```

common: fix initialization order of FileHandler members

---

src/RBF/rbf.hpp

Fixes the following warning:
```
In file included from /opt/bitpit/code/src/RBF/rbf.cpp:34:0: 
/opt/bitpit/code/src/RBF/rbf.hpp: In copy constructor ‘bitpit::RBFKernel::RBFKernel(const bitpit::RBFKernel&)’: /opt/bitpit/code/src/RBF/rbf.hpp:109:22: warning: ‘bitpit::RBFKernel::m_polyActiveBasis’ will be initialized after [-Wreorder]
std::vector<int> m_polyActiveBasis;             /**< Active terms of linear polynomial, 0 is constant, i+1 the i-th system coordinate */
^~~~~~~~~~~~~~~~~
/opt/bitpit/code/src/RBF/rbf.hpp:108:22: warning:   ‘bitpit::RBFKernel::LinearPolynomial bitpit::RBFKernel::m_polynomial’ [-Wreorder]
LinearPolynomial m_polynomial;                  /**< Linear polynomial object */
^~~~~~~~~~~~
/opt/bitpit/code/src/RBF/rbf.cpp:87:1: warning:   when initialized here …
```

RBF: fix initialization order of RBF members

---

test/integration_tests/volunstructured/test_volunstructured_parallel_00001.cpp
test/integration_tests/volunstructured/test_volunstructured_parallel_00002.cpp

This should allow MSVC to select the right constructor VolUnstructured.

test/volunstructured: explicitly declare a variable for the halo size

---

src/LA/system_matrix.cpp
src/LA/system_matrix.hpp

The communicator needs to be copied with the proper MPI functions.

LA: add an explict copy costructor to SparseMatrix

---

.github/workflows/continuous_integration.yml

This should fix the following warning:
```Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see...```

cicd: bump version of github checkout action to v4

---

src/levelset/levelSetObject.cpp
src/levelset/levelSetSegmentationObject.cpp
src/levelset/levelSetSegmentationObject.hpp

Some fixes gathered in the last weeks:
- fixed the check that identifies if a point is inside the narrow band;
- improved robustness of unsigned distance evaluation;
- small optimization in sign propagation.

levelset: miscellaneous fixes

---

src/PABLO/LocalTree.cpp
test/integration_tests/PABLO/test_PABLO_00005.cpp

The LocalTree::refine function can be called several times in a row. Therefore, it should properly update the mapper received in input rather than creating a new map from scratch.

PABLO: fix mapping when refine function is called mutliple times

---

src/levelset/levelSetCache.hpp
src/levelset/levelSetCache.tpp
src/levelset/levelSetObject.cpp
src/levelset/levelSetObject.hpp
src/levelset/levelSetObject.tpp
src/levelset/levelSetOctreeKernel.cpp
src/levelset/levelSetSegmentationObject.cpp
src/levelset/levelSetSegmentationObject.hpp
src/levelset/levelSetUnstructuredKernel.cpp

The index associated with the caches should be preserved during the dump/restore procedure.

levelset: fix dump/restore of caches 

---

src/containers/binary_stream.cpp
src/containers/binary_stream.hpp
src/containers/binary_stream.tpp
test/unit_tests/containers/CMakeLists.txt
test/unit_tests/containers/test_binary_stream.cpp
test/unit_tests/helpers/unit_test.hpp

Having operators for streaming containers of the standard library seems useful.

containers: add binary stream operators for containers of the standard library

---

src/communications/communications.cpp
src/communications/communications.hpp

Add two methods to get rank and number of processes.

Get rank and processes count from DataCommunicator

---

src/LA/system_solvers_large.cpp

When the argument "flatten" is set to true, block size will not be taken into account when allocating the internal storage of the system matrix. Even when the internal storage is flat, block size information are available and can be used by the solver to speed up the solution of the system. However, since the internal storage doesn't take blocks into account, some low level operations (e.g., matrix-matrix multiplications) cannot use block information. Some algorithms for the solution of the system (e.g., mutligrid) requires a flat storage.

LA: set block size information even when a flat internal storage is used

---

src/PABLO/ParaTree.cpp
src/PABLO/ParaTree.hpp
src/patchkernel/patch_kernel.cpp
src/patchkernel/patch_kernel.hpp
test/integration_tests/PABLO/CMakeLists.txt
test/integration_tests/PABLO/test_PABLO_parallel_00007.cpp

If the owner of the point is an internal octant, decrementing the Morton upper bound by one will give us the requested octant. If the owner of the point is a ghost octant, we need to test all the octants before the Morton upper bound.

PABLO: rework the function that evaluates the octant owner of a point

---

src/patchkernel/patch_kernel.cpp
src/patchkernel/patch_kernel.hpp
src/volcartesian/volcartesian.cpp
src/volcartesian/volcartesian.hpp
src/voloctree/voloctree.cpp
src/voloctree/voloctree.hpp

The function "spawn" is now obsolete, the first update of the patch will take care of the initialization.
Depends on #371 and #370.

patchkernel: simplify initialization of the patch

---

src/LA/system_solvers_large.cpp
src/LA/system_solvers_large.hpp
src/common/compiler.hpp
src/discretization/stencil_weight.hpp

Since void_t is the only C++17 feature used in bitpit, this change will allow to keep C++11 compatibility.

common: add a custom implementation of std::void_t for C++11 backwards compatibility

---

src/LA/system_solvers_large.cpp

KSP/PC options should be set before calling KSPSetFromOptions/PCSetFromOptions.

LA: fix initialization of PETSc KSP

---

src/patchkernel/surface_kernel.cpp

patchkernel: silence warning about comparison of integer of different signedness

---

src/PABLO/LocalTree.cpp
src/PABLO/Octant.cpp

The flag Octant::INFO_NEW4REFINEMENT should only be set for the octants that are generated after a refinement.

PABLO: mark octants as "new for refinement" only if they are generated by a refinement

---

src/patchkernel/surface_kernel.cpp

CG functions expect vertices ordered in CCW order.

patchkernel: fix evaluation of barycentric coordinates

---

src/volcartesian/volcartesian.cpp
test/unit_tests/volcartesian/test_volcartesian_general.cpp

After switching to normal memory mode, we need to update the patch to make sure all data structures (e.g. interfaces) are properly updated.

 volcartesian: properly update patch data structures when switching memory mode

---

src/CG/CG.hpp
src/CG/CG_elem.cpp
src/levelset/levelSetCommon.hpp
src/levelset/levelSetObject.cpp
src/levelset/levelSetObject.hpp
src/levelset/levelSetSegmentationObject.cpp
src/levelset/levelSetSegmentationObject.hpp
src/operators/Operators.tpp
src/patchkernel/cell.cpp
src/patchkernel/cell.hpp
src/patchkernel/patch_kernel.cpp
src/patchkernel/patch_kernel.hpp
test/integration_tests/levelset/test_levelset_00001.cpp
test/integration_tests/levelset/test_levelset_00002.cpp

1. Introduce the pixel, triangle and polygon intersection with plane.
2. Allow the intersection of interfaces with smoothed continuous surface. It's mandatory for the conversion of Immerflow to a cut-cell software.

levelset: interface intersection

---

environments/ubuntu/Dockerfile

Boost sources should be downloaded from the official repository. The repository we are using right now (jfrog) doesn't work anymore.

cicd: download Boost from the official repository

---

src/levelset/levelSetObject.cpp

The value stored in the cache is an absolute value, we cannot use it to evaluate the sign.

levelset: fix evaluation of cell sign in the bulk

---

CMakeLists.txt
cmake/CopyDependencies.cmake
cmake/DependencyResolution.cmake
cmake/SelfContainment.cmake
cmake/WindowsRuntime.cmake

Self-containment is an optional feature that copies a curated list of third-party libraries in the installation directory and forces bitpit to use the symbols contained in these libraries in preference to global symbols with the same name. The directory to which third-party libraries are copied should be customizable by the user (potentially multiple applications may use the same directory to store third-party libraries).
Relevant CMake variables are:
BITPIT_ENABLE_SELF_CONTAINMENT: allows to enable self containment;
BITPIT_SELF_CONTAINMENT_THIRD_PARTY_DIR: specify the directory where third-party libraries will be copied (the path is relative to the CMAKE_INSTALL_PREFIX directory).
To ensure that the symbols contained in the collected third-party libraries are preferred over the global …

cmake: add support for self-containment

---

CMakeLists.txt

If MPI support is enabled, MPI is a required package.

cmake: raise an error if the MPI package is not found

---

cmake/BITPITConfig.cmake.in

This change avoid hard-coding paths in "BITPITConfig.cmake".

cmake: get CMake files location using the proper CMake variable

---

CMakeLists.txt
external/PETSc/cmake/FindPETSc.cmake

With this change, the CMake-generated target file will no longer explicitly contain the PETSc include paths.

cmake: add PETSc imported targets

---

CMakeLists.txt
external/METIS/cmake/FindMETIS.cmake
external/PETSc/cmake/FindPETSc.cmake

With this change, the CMake-generated target file will no longer explicitly contain the METIS include paths.
Depends on #484.

cmake: add METIS imported targets
